#ifndef A111m3_integral_codegen_contour_deformation_sector_2_order_0_hpp_included
#define A111m3_integral_codegen_contour_deformation_sector_2_order_0_hpp_included
#include "A111m3_integral.hpp"
#include "functions.hpp"
namespace A111m3_integral
{
secdecutil::SectorContainerWithDeformation<real_t, complex_t>::DeformedIntegrandFunction sector_2_order_0_contour_deformation_polynomial;
};
#endif
