integralfamilies:

  - name: "tree"
    loop_momenta: []

  # for boxes etc.
  - name: "A"
    loop_momenta: [k]
    propagators:
      - [ "k",        0   ]
      - [ "k-p1",     0   ]
      - [ "k-p1-p2",  0   ]
      - [ "k-p3",    "mt^2" ]

  # for heavy quark vertex correction etc.
  - name: "B"
    loop_momenta: [k]
    propagators:
      - [ "k",       "mt^2" ]
      - [ "k-p1",     0   ]
      - [ "k-p1-p2", "mt^2" ]
      - [ "k-p3",     0   ]
