integralfamilies:

  - name: "tree"
    loop_momenta: []

  # for boxes etc.
  - name: "Zbox"
    loop_momenta: [k]
    propagators:
      - [ "k",       "mt^2" ]
      - [ "k-p1",    "mt^2" ]
      - [ "k-p1-p2", "mt^2" ]
      - [ "k-p3",    "mZ^2" ]

  - name: "hbox"
    loop_momenta: [k]
    propagators:
      - [ "k",       "mt^2" ]
      - [ "k-p1",    "mt^2" ]
      - [ "k-p1-p2", "mt^2" ]
      - [ "k-p3",    "mh^2" ]

  - name: "Wbox"
    loop_momenta: [k]
    propagators:
      - [ "k",       0      ]
      - [ "k-p1",    0      ]
      - [ "k-p1-p2", 0      ]
      - [ "k-p3",    "mW^2" ]


  # Z-boson bubble (top topology)
  - name: "Zbub"
    loop_momenta: [k]
    propagators:
      - [ "k",       "mZ^2" ]
      - [ "k-p1",    0	    ]
      - [ "k-p1-p2", "mZ^2" ]
      - [ "k-p3",    0	    ]