jobs:
  - reduce_sectors:
      sector_selection:
        select_recursively:
          - [Zbox, 15]
          - [hbox, 15]
          - [Wbox, 15]
          - [Zbub, 5 ]
      identities: 
        ibp: &myrsranges    # define label myrsranges for later reference
          - { r: [t, 4], s: [0, 2] }
      solutions:
        requested_solutions: *myrsranges    # selects the above defined ranges
#      reduzer_options:
#        use_database: false
