---
kinematics:
  incoming_momenta: [p1, p2]
  outgoing_momenta: [p3, p4]
  momentum_conservation: [p4, p1 + p2 - p3]
  kinematic_invariants:
    - [mt, 1]
    - [s,  2]
    - [t,  2]
  scalarproduct_rules:
    - [[p1,p1],  "0"]
    - [[p2,p2],  "0"]
    - [[p3,p3],  mt^2]
    - [[p1+p2, p1+p2], s]
    - [[p1-p3, p1-p3], t]
    - [[p2-p3, p2-p3], -s-t+2*mt^2] # == u
#  symbol_to_replace_by_one: mt
