#ifndef A1111_integral_codegen_contour_deformation_sector_7_order_0_hpp_included
#define A1111_integral_codegen_contour_deformation_sector_7_order_0_hpp_included
#include "A1111_integral.hpp"
#include "functions.hpp"
namespace A1111_integral
{
secdecutil::SectorContainerWithDeformation<real_t, complex_t>::DeformedIntegrandFunction sector_7_order_0_contour_deformation_polynomial;
};
#endif
