#include "sector_2_1.hpp"
namespace bubble2l
{
#ifdef SECDEC_WITH_CUDA
__host__ __device__
#endif
integrand_return_t sector_2_order_1_integrand
(
real_t const * const integration_variables,
real_t const * const real_parameters,
complex_t const * const complex_parameters
,real_t const * const deformation_parameters
)
{
#define x0 integration_variables[0]
#define x1 integration_variables[1]
#define x2 integration_variables[2]
#define x3 integration_variables[3]
#define s real_parameters[0]
#define m2 real_parameters[1]
#define SecDecInternalLambda0 deformation_parameters[0]
#define SecDecInternalLambda1 deformation_parameters[1]
#define SecDecInternalLambda2 deformation_parameters[2]
#define SecDecInternalLambda3 deformation_parameters[3]
#define SecDecInternalDenominator(x) 1./(x)
#ifdef SECDEC_WITH_CUDA
#define SecDecInternalRealPart(x) (complex_t{x}).real()
#define SecDecInternalImagPart(x) (complex_t{x}).imag()
#else
#define SecDecInternalRealPart(x) std::real(x)
#define SecDecInternalImagPart(x) std::imag(x)
#endif
#define tmp SecDecInternalAbbreviation[0]
#define SecDecInternalAbbreviations2(ID) SecDecInternalAbbreviation[ID]

integrand_return_t SecDecInternalAbbreviation[25 + 1];
integrand_return_t SecDecInternalSecondAbbreviation[sector_2_order_1_optimmaxvar_second + 1];

SecDecInternalAbbreviation[1]=x0 + 1.E+0;SecDecInternalAbbreviation[2]=SecDecInternalAbbreviation[1] + x1;SecDecInternalAbbreviation[3]=2.E+0*x3;SecDecInternalAbbreviation[4]=SecDecInternalAbbreviation[2]*SecDecInternalAbbreviation[3];SecDecInternalAbbreviation[5]=2.E+0*x0;SecDecInternalAbbreviation[6]=SecDecInternalAbbreviation[5] + 1.E+0;SecDecInternalAbbreviation[4]=SecDecInternalAbbreviation[4] +SecDecInternalAbbreviation[6];SecDecInternalAbbreviation[7]=2.E+0*x1 +SecDecInternalAbbreviation[4];SecDecInternalAbbreviation[8]=SecDecInternalAbbreviation[7]*x2;SecDecInternalAbbreviation[2]=SecDecInternalAbbreviation[2] + x3;SecDecInternalAbbreviation[8]=SecDecInternalAbbreviation[8] + 2.E+0*SecDecInternalAbbreviation[2];SecDecInternalAbbreviation[8]=SecDecInternalAbbreviation[8]*m2;SecDecInternalAbbreviation[9]=x3 + 1.E+0;SecDecInternalAbbreviation[10]=SecDecInternalAbbreviation[9]*s;SecDecInternalAbbreviation[8]=SecDecInternalAbbreviation[8] -SecDecInternalAbbreviation[10];SecDecInternalAbbreviation[10]=m2*x2;SecDecInternalAbbreviation[7]=SecDecInternalAbbreviation[7]*m2;SecDecInternalAbbreviation[11]=SecDecInternalAbbreviation[9]*x2;SecDecInternalAbbreviation[11]=SecDecInternalAbbreviation[11] +1.E+0;SecDecInternalAbbreviation[12]=2.E+0*m2;SecDecInternalAbbreviation[13]=SecDecInternalAbbreviation[11]*SecDecInternalAbbreviation[12];SecDecInternalAbbreviation[14]=x1 + x0;SecDecInternalAbbreviation[15]=SecDecInternalAbbreviation[14]*x3;SecDecInternalAbbreviation[1]=SecDecInternalAbbreviation[1]*x1;SecDecInternalAbbreviation[16]=SecDecInternalAbbreviation[1] + x0;SecDecInternalAbbreviation[15]=SecDecInternalAbbreviation[15] +SecDecInternalAbbreviation[16];SecDecInternalAbbreviation[17]=x2*SecDecInternalAbbreviation[15];SecDecInternalAbbreviation[17]=SecDecInternalAbbreviation[17] +SecDecInternalAbbreviation[2];SecDecInternalAbbreviation[17]=SecDecInternalAbbreviation[17]*SecDecInternalAbbreviation[12];SecDecInternalAbbreviation[18]=s*SecDecInternalAbbreviation[14];SecDecInternalAbbreviation[17]=SecDecInternalAbbreviation[17] -SecDecInternalAbbreviation[18];SecDecInternalAbbreviation[2]=SecDecInternalAbbreviation[2]*x2;SecDecInternalAbbreviation[2]=SecDecInternalAbbreviation[2] + 1.E+0;SecDecInternalAbbreviation[2]=SecDecInternalAbbreviation[2]*SecDecInternalAbbreviation[12];SecDecInternalAbbreviation[2]=SecDecInternalAbbreviation[2] - s;SecDecInternalAbbreviation[16]=SecDecInternalAbbreviation[16]*SecDecInternalAbbreviation[3];SecDecInternalAbbreviation[6]=SecDecInternalAbbreviation[6]*x1;SecDecInternalAbbreviation[6]=x0 + SecDecInternalAbbreviation[16] +SecDecInternalAbbreviation[6];SecDecInternalAbbreviation[16]=m2*SecDecInternalAbbreviation[6];SecDecInternalAbbreviation[19]=m2*SecDecInternalAbbreviation[14];SecDecInternalAbbreviation[20]=SecDecInternalAbbreviation[9]*m2;SecDecInternalAbbreviation[15]=SecDecInternalAbbreviation[15]*SecDecInternalAbbreviation[12];SecDecInternalAbbreviation[14]=SecDecInternalAbbreviation[14]*x2;SecDecInternalAbbreviation[14]=SecDecInternalAbbreviation[14] +1.E+0;SecDecInternalAbbreviation[21]=SecDecInternalAbbreviation[14]*SecDecInternalAbbreviation[12];SecDecInternalAbbreviation[6]=x2*SecDecInternalAbbreviation[6];SecDecInternalAbbreviation[1]=SecDecInternalAbbreviation[6] + 2.E+0*SecDecInternalAbbreviation[1] + SecDecInternalAbbreviation[4];SecDecInternalAbbreviation[1]=m2*SecDecInternalAbbreviation[1];SecDecInternalAbbreviation[4]= - SecDecInternalAbbreviation[18]*SecDecInternalAbbreviation[9];SecDecInternalAbbreviation[1]=SecDecInternalAbbreviation[1] +SecDecInternalAbbreviation[4];SecDecInternalAbbreviation[4]=m2*SecDecInternalAbbreviation[14];SecDecInternalAbbreviation[6]=SecDecInternalAbbreviation[11]*m2;SecDecInternalAbbreviation[9]=SecDecInternalAbbreviation[12] - s;SecDecInternalAbbreviation[11]=x2*SecDecInternalLambda2;SecDecInternalAbbreviation[14]= - SecDecInternalLambda2 +SecDecInternalAbbreviation[11];SecDecInternalAbbreviation[18]=x3*SecDecInternalLambda3;SecDecInternalAbbreviation[3]= - 1.E+0 +SecDecInternalAbbreviation[3];SecDecInternalAbbreviation[3]=SecDecInternalLambda3*SecDecInternalAbbreviation[3];SecDecInternalAbbreviation[22]= - SecDecInternalLambda2 + 2.E+0*SecDecInternalAbbreviation[11];SecDecInternalAbbreviation[23]=x1*SecDecInternalLambda1;SecDecInternalAbbreviation[24]= - SecDecInternalLambda1 + 2.E+0*SecDecInternalAbbreviation[23];SecDecInternalAbbreviation[5]= - 1.E+0 +SecDecInternalAbbreviation[5];SecDecInternalAbbreviation[5]=SecDecInternalLambda0*SecDecInternalAbbreviation[5];SecDecInternalAbbreviation[25]=x0*SecDecInternalLambda0;



// begin next dependency level
SecDecInternalSecondAbbreviation[1]=SecDecInternalAbbreviations2(2);SecDecInternalSecondAbbreviation[2]=SecDecInternalAbbreviations2(21);SecDecInternalSecondAbbreviation[3]=SecDecInternalAbbreviations2(13);

auto SecDecInternalddFd1d3Call1 =SecDecInternalSecondAbbreviation[1];
auto SecDecInternalddFd3d3Call1 =SecDecInternalSecondAbbreviation[2];
auto SecDecInternalddFd1d1Call1 =SecDecInternalSecondAbbreviation[3];
auto SecDecInternalddFd0d3Call1 =SecDecInternalSecondAbbreviation[1];
auto SecDecInternalddFd0d1Call1 =SecDecInternalSecondAbbreviation[3];
auto SecDecInternalddFd0d0Call1 =SecDecInternalSecondAbbreviation[3];
auto SecDecInternallogCall1 =log(x2);
auto SecDecInternalSecDecInternalPowCall1 =pow(x0,2);
auto SecDecInternalSecDecInternalPowCall2 =pow(x1,2);
auto SecDecInternalSecDecInternalPowCall3 =pow(x2,2);
auto SecDecInternalSecDecInternalPowCall4 =pow(x3,2);


// begin next dependency level
SecDecInternalSecondAbbreviation[1]=SecDecInternalAbbreviations2(15);SecDecInternalSecondAbbreviation[2]=SecDecInternalAbbreviations2(8);SecDecInternalSecondAbbreviation[3]=SecDecInternalAbbreviations2(10);SecDecInternalSecondAbbreviation[4]=SecDecInternalAbbreviations2(1);SecDecInternalSecondAbbreviation[5]=SecDecInternalAbbreviations2(4);SecDecInternalSecondAbbreviation[6]=SecDecInternalAbbreviations2(6);SecDecInternalSecondAbbreviation[7]=SecDecInternalAbbreviations2(16);SecDecInternalSecondAbbreviation[8]=SecDecInternalAbbreviations2(19);SecDecInternalSecondAbbreviation[9]=SecDecInternalAbbreviations2(20);SecDecInternalSecondAbbreviation[10]=SecDecInternalAbbreviations2(17);SecDecInternalSecondAbbreviation[11]=SecDecInternalAbbreviations2(7);SecDecInternalSecondAbbreviation[12]=SecDecInternalSecDecInternalPowCall1 + SecDecInternalSecDecInternalPowCall2;SecDecInternalSecondAbbreviation[13]=m2*SecDecInternalSecondAbbreviation[12];SecDecInternalSecondAbbreviation[13]=SecDecInternalSecondAbbreviation[13] + SecDecInternalSecondAbbreviation[1];SecDecInternalSecondAbbreviation[14]=SecDecInternalSecondAbbreviation[3]*SecDecInternalSecDecInternalPowCall4;SecDecInternalSecondAbbreviation[14]=SecDecInternalSecondAbbreviation[14] + SecDecInternalSecondAbbreviation[2];SecDecInternalSecondAbbreviation[15]=SecDecInternalSecondAbbreviation[6]*SecDecInternalSecondAbbreviation[12];SecDecInternalSecondAbbreviation[16]=SecDecInternalSecondAbbreviation[5]*SecDecInternalSecDecInternalPowCall4;SecDecInternalSecondAbbreviation[15]=SecDecInternalSecondAbbreviation[16] + SecDecInternalSecondAbbreviation[15] + SecDecInternalSecondAbbreviation[4];SecDecInternalSecondAbbreviation[16]=SecDecInternalSecondAbbreviation[9]*SecDecInternalSecondAbbreviation[12];SecDecInternalSecondAbbreviation[17]=SecDecInternalSecondAbbreviation[8]*SecDecInternalSecDecInternalPowCall4;SecDecInternalSecondAbbreviation[16]=SecDecInternalSecondAbbreviation[17] + SecDecInternalSecondAbbreviation[16] + SecDecInternalSecondAbbreviation[7];SecDecInternalSecondAbbreviation[12]=SecDecInternalSecondAbbreviation[3]*SecDecInternalSecondAbbreviation[12];SecDecInternalSecondAbbreviation[12]=SecDecInternalSecondAbbreviation[10] + SecDecInternalSecondAbbreviation[12];SecDecInternalSecondAbbreviation[17]=m2*SecDecInternalSecDecInternalPowCall4;SecDecInternalSecondAbbreviation[17]=SecDecInternalSecondAbbreviation[17] + SecDecInternalSecondAbbreviation[11];

auto SecDecInternalddFd2d3Call1 =SecDecInternalSecondAbbreviation[13];
auto SecDecInternaldFd1Call1 =SecDecInternalSecondAbbreviation[14];
auto SecDecInternalFCall2 =SecDecInternalSecondAbbreviation[15];
auto SecDecInternaldFd2Call1 =SecDecInternalSecondAbbreviation[16];
auto SecDecInternaldFd3Call1 =SecDecInternalSecondAbbreviation[12];
auto SecDecInternalddFd1d2Call1 =SecDecInternalSecondAbbreviation[17];
auto SecDecInternalddFd0d2Call1 =SecDecInternalSecondAbbreviation[17];
auto SecDecInternaldFd0Call1 =SecDecInternalSecondAbbreviation[14];
auto SecDecInternallogCall2 =log(SecDecInternalSecDecInternalPowCall3);
auto SecDecInternalSecDecInternalRealPartCall2 =SecDecInternalRealPart(SecDecInternalddFd1d3Call1);
auto SecDecInternalSecDecInternalRealPartCall3 =SecDecInternalRealPart(SecDecInternalddFd3d3Call1);
auto SecDecInternalSecDecInternalRealPartCall5 =SecDecInternalRealPart(SecDecInternalddFd1d1Call1);
auto SecDecInternalSecDecInternalRealPartCall7 =SecDecInternalRealPart(SecDecInternalddFd0d3Call1);
auto SecDecInternalSecDecInternalRealPartCall9 =SecDecInternalRealPart(SecDecInternalddFd0d1Call1);
auto SecDecInternalSecDecInternalRealPartCall11 =SecDecInternalRealPart(SecDecInternalddFd0d0Call1);


// begin next dependency level
SecDecInternalSecondAbbreviation[1]=SecDecInternalAbbreviations2(25);SecDecInternalSecondAbbreviation[2]=SecDecInternalAbbreviations2(23);SecDecInternalSecondAbbreviation[3]=SecDecInternalAbbreviations2(18);SecDecInternalSecondAbbreviation[4]=SecDecInternalSecDecInternalPowCall1*SecDecInternalLambda0;SecDecInternalSecondAbbreviation[4]=SecDecInternalSecondAbbreviation[4] - SecDecInternalSecondAbbreviation[1];SecDecInternalSecondAbbreviation[5]=i_*SecDecInternalSecDecInternalRealPartCall7;SecDecInternalSecondAbbreviation[6]=SecDecInternalSecondAbbreviation[4]*SecDecInternalSecondAbbreviation[5];SecDecInternalSecondAbbreviation[7]=i_*SecDecInternalSecDecInternalRealPartCall9;SecDecInternalSecondAbbreviation[4]=SecDecInternalSecondAbbreviation[4]*SecDecInternalSecondAbbreviation[7];SecDecInternalSecondAbbreviation[8]=SecDecInternalSecDecInternalPowCall2*SecDecInternalLambda1;SecDecInternalSecondAbbreviation[8]=SecDecInternalSecondAbbreviation[8] - SecDecInternalSecondAbbreviation[2];SecDecInternalSecondAbbreviation[9]=i_*SecDecInternalSecDecInternalRealPartCall2;SecDecInternalSecondAbbreviation[10]=SecDecInternalSecondAbbreviation[8]*SecDecInternalSecondAbbreviation[9];SecDecInternalSecondAbbreviation[7]=SecDecInternalSecondAbbreviation[8]*SecDecInternalSecondAbbreviation[7];SecDecInternalSecondAbbreviation[8]=SecDecInternalSecDecInternalPowCall4*SecDecInternalLambda3;SecDecInternalSecondAbbreviation[8]=SecDecInternalSecondAbbreviation[8] - SecDecInternalSecondAbbreviation[3];SecDecInternalSecondAbbreviation[9]=SecDecInternalSecondAbbreviation[8]*SecDecInternalSecondAbbreviation[9];SecDecInternalSecondAbbreviation[5]=SecDecInternalSecondAbbreviation[8]*SecDecInternalSecondAbbreviation[5];

auto SecDecInternaldSecDecInternalDeformedx0d3Call1 =SecDecInternalSecondAbbreviation[6];
auto SecDecInternaldSecDecInternalDeformedx0d1Call1 =SecDecInternalSecondAbbreviation[4];
auto SecDecInternaldSecDecInternalDeformedx1d3Call1 =SecDecInternalSecondAbbreviation[10];
auto SecDecInternaldSecDecInternalDeformedx1d0Call1 =SecDecInternalSecondAbbreviation[7];
auto SecDecInternaldSecDecInternalDeformedx3d1Call1 =SecDecInternalSecondAbbreviation[9];
auto SecDecInternaldSecDecInternalDeformedx3d0Call1 =SecDecInternalSecondAbbreviation[5];
auto SecDecInternalSecDecInternalRealPartCall1 =SecDecInternalRealPart(SecDecInternaldFd1Call1);
auto SecDecInternalSecDecInternalRealPartCall4 =SecDecInternalRealPart(SecDecInternalddFd2d3Call1);
auto SecDecInternalSecDecInternalRealPartCall6 =SecDecInternalRealPart(SecDecInternaldFd2Call1);
auto SecDecInternalSecDecInternalRealPartCall8 =SecDecInternalRealPart(SecDecInternaldFd3Call1);
auto SecDecInternalSecDecInternalRealPartCall10 =SecDecInternalRealPart(SecDecInternalddFd1d2Call1);
auto SecDecInternalSecDecInternalRealPartCall12 =SecDecInternalRealPart(SecDecInternalddFd0d2Call1);
auto SecDecInternalSecDecInternalRealPartCall13 =SecDecInternalRealPart(SecDecInternaldFd0Call1);


// begin next dependency level
SecDecInternalSecondAbbreviation[1]=SecDecInternalAbbreviations2(14);SecDecInternalSecondAbbreviation[2]=SecDecInternalAbbreviations2(25);SecDecInternalSecondAbbreviation[3]=SecDecInternalAbbreviations2(5);SecDecInternalSecondAbbreviation[4]=SecDecInternalAbbreviations2(23);SecDecInternalSecondAbbreviation[5]=SecDecInternalAbbreviations2(24);SecDecInternalSecondAbbreviation[6]=SecDecInternalAbbreviations2(11);SecDecInternalSecondAbbreviation[7]=SecDecInternalAbbreviations2(22);SecDecInternalSecondAbbreviation[8]=SecDecInternalAbbreviations2(18);SecDecInternalSecondAbbreviation[9]=SecDecInternalAbbreviations2(3);SecDecInternalSecondAbbreviation[10]=i_*SecDecInternalSecDecInternalRealPartCall6;SecDecInternalSecondAbbreviation[11]=SecDecInternalSecondAbbreviation[1]*SecDecInternalSecondAbbreviation[10];SecDecInternalSecondAbbreviation[11]=1.E+0 + SecDecInternalSecondAbbreviation[11];SecDecInternalSecondAbbreviation[12]=SecDecInternalSecDecInternalPowCall1*SecDecInternalLambda0;SecDecInternalSecondAbbreviation[12]=SecDecInternalSecondAbbreviation[12] - SecDecInternalSecondAbbreviation[2];SecDecInternalSecondAbbreviation[13]=SecDecInternalSecondAbbreviation[12]*i_;SecDecInternalSecondAbbreviation[14]=SecDecInternalSecDecInternalRealPartCall13*SecDecInternalSecondAbbreviation[13];SecDecInternalSecondAbbreviation[14]=x0 + SecDecInternalSecondAbbreviation[14];SecDecInternalSecondAbbreviation[13]=SecDecInternalSecDecInternalRealPartCall12*SecDecInternalSecondAbbreviation[13];SecDecInternalSecondAbbreviation[12]=SecDecInternalSecDecInternalRealPartCall11*SecDecInternalSecondAbbreviation[12];SecDecInternalSecondAbbreviation[15]=SecDecInternalSecDecInternalRealPartCall13*SecDecInternalSecondAbbreviation[3];SecDecInternalSecondAbbreviation[12]=SecDecInternalSecondAbbreviation[15] + SecDecInternalSecondAbbreviation[12];SecDecInternalSecondAbbreviation[12]=i_*SecDecInternalSecondAbbreviation[12];SecDecInternalSecondAbbreviation[12]=1.E+0 + SecDecInternalSecondAbbreviation[12];SecDecInternalSecondAbbreviation[15]=SecDecInternalSecDecInternalPowCall2*SecDecInternalLambda1;SecDecInternalSecondAbbreviation[15]=SecDecInternalSecondAbbreviation[15] - SecDecInternalSecondAbbreviation[4];SecDecInternalSecondAbbreviation[16]=SecDecInternalSecondAbbreviation[15]*i_;SecDecInternalSecondAbbreviation[17]=SecDecInternalSecDecInternalRealPartCall1*SecDecInternalSecondAbbreviation[16];SecDecInternalSecondAbbreviation[17]=x1 + SecDecInternalSecondAbbreviation[17];SecDecInternalSecondAbbreviation[15]=SecDecInternalSecDecInternalRealPartCall5*SecDecInternalSecondAbbreviation[15];SecDecInternalSecondAbbreviation[18]=SecDecInternalSecDecInternalRealPartCall1*SecDecInternalSecondAbbreviation[5];SecDecInternalSecondAbbreviation[15]=SecDecInternalSecondAbbreviation[18] + SecDecInternalSecondAbbreviation[15];SecDecInternalSecondAbbreviation[15]=i_*SecDecInternalSecondAbbreviation[15];SecDecInternalSecondAbbreviation[15]=1.E+0 + SecDecInternalSecondAbbreviation[15];SecDecInternalSecondAbbreviation[16]=SecDecInternalSecDecInternalRealPartCall10*SecDecInternalSecondAbbreviation[16];SecDecInternalSecondAbbreviation[18]=SecDecInternalSecDecInternalPowCall3*SecDecInternalLambda2;SecDecInternalSecondAbbreviation[18]=SecDecInternalSecondAbbreviation[18] - SecDecInternalSecondAbbreviation[6];SecDecInternalSecondAbbreviation[18]=SecDecInternalSecondAbbreviation[18]*i_;SecDecInternalSecondAbbreviation[19]=SecDecInternalSecDecInternalRealPartCall6*SecDecInternalSecondAbbreviation[18];SecDecInternalSecondAbbreviation[19]=x2 + SecDecInternalSecondAbbreviation[19];SecDecInternalSecondAbbreviation[20]=SecDecInternalSecDecInternalRealPartCall4*SecDecInternalSecondAbbreviation[18];SecDecInternalSecondAbbreviation[21]=SecDecInternalSecDecInternalRealPartCall10*SecDecInternalSecondAbbreviation[18];SecDecInternalSecondAbbreviation[10]=SecDecInternalSecondAbbreviation[7]*SecDecInternalSecondAbbreviation[10];SecDecInternalSecondAbbreviation[10]=1.E+0 + SecDecInternalSecondAbbreviation[10];SecDecInternalSecondAbbreviation[18]=SecDecInternalSecDecInternalRealPartCall12*SecDecInternalSecondAbbreviation[18];SecDecInternalSecondAbbreviation[22]=SecDecInternalSecDecInternalPowCall4*SecDecInternalLambda3;SecDecInternalSecondAbbreviation[22]=SecDecInternalSecondAbbreviation[22] - SecDecInternalSecondAbbreviation[8];SecDecInternalSecondAbbreviation[23]=SecDecInternalSecondAbbreviation[22]*i_;SecDecInternalSecondAbbreviation[24]=SecDecInternalSecDecInternalRealPartCall8*SecDecInternalSecondAbbreviation[23];SecDecInternalSecondAbbreviation[24]=x3 + SecDecInternalSecondAbbreviation[24];SecDecInternalSecondAbbreviation[22]=SecDecInternalSecDecInternalRealPartCall3*SecDecInternalSecondAbbreviation[22];SecDecInternalSecondAbbreviation[25]=SecDecInternalSecDecInternalRealPartCall8*SecDecInternalSecondAbbreviation[9];SecDecInternalSecondAbbreviation[22]=SecDecInternalSecondAbbreviation[25] + SecDecInternalSecondAbbreviation[22];SecDecInternalSecondAbbreviation[22]=i_*SecDecInternalSecondAbbreviation[22];SecDecInternalSecondAbbreviation[22]=1.E+0 + SecDecInternalSecondAbbreviation[22];SecDecInternalSecondAbbreviation[23]=SecDecInternalSecDecInternalRealPartCall4*SecDecInternalSecondAbbreviation[23];

auto SecDecInternalSecDecInternalCondefFacx2Call1 =SecDecInternalSecondAbbreviation[11];
auto SecDecInternalSecDecInternalDeformedx0Call1 =SecDecInternalSecondAbbreviation[14];
auto SecDecInternaldSecDecInternalDeformedx0d2Call1 =SecDecInternalSecondAbbreviation[13];
auto SecDecInternaldSecDecInternalDeformedx0d0Call1 =SecDecInternalSecondAbbreviation[12];
auto SecDecInternalSecDecInternalDeformedx1Call1 =SecDecInternalSecondAbbreviation[17];
auto SecDecInternaldSecDecInternalDeformedx1d1Call1 =SecDecInternalSecondAbbreviation[15];
auto SecDecInternaldSecDecInternalDeformedx1d2Call1 =SecDecInternalSecondAbbreviation[16];
auto SecDecInternalSecDecInternalDeformedx2Call1 =SecDecInternalSecondAbbreviation[19];
auto SecDecInternaldSecDecInternalDeformedx2d3Call1 =SecDecInternalSecondAbbreviation[20];
auto SecDecInternaldSecDecInternalDeformedx2d1Call1 =SecDecInternalSecondAbbreviation[21];
auto SecDecInternaldSecDecInternalDeformedx2d2Call1 =SecDecInternalSecondAbbreviation[10];
auto SecDecInternaldSecDecInternalDeformedx2d0Call1 =SecDecInternalSecondAbbreviation[18];
auto SecDecInternalSecDecInternalDeformedx3Call1 =SecDecInternalSecondAbbreviation[24];
auto SecDecInternaldSecDecInternalDeformedx3d3Call1 =SecDecInternalSecondAbbreviation[22];
auto SecDecInternaldSecDecInternalDeformedx3d2Call1 =SecDecInternalSecondAbbreviation[23];


// begin next dependency level
SecDecInternalSecondAbbreviation[1]=SecDecInternalSecDecInternalDeformedx0Call1 + SecDecInternalSecDecInternalDeformedx1Call1;SecDecInternalSecondAbbreviation[2]=SecDecInternalSecDecInternalDeformedx3Call1 + 1.E+0;SecDecInternalSecondAbbreviation[3]=SecDecInternalSecondAbbreviation[2]*SecDecInternalSecDecInternalDeformedx2Call1;SecDecInternalSecondAbbreviation[3]=SecDecInternalSecondAbbreviation[3] + 1.E+0;SecDecInternalSecondAbbreviation[1]=SecDecInternalSecondAbbreviation[3]*SecDecInternalSecondAbbreviation[1];SecDecInternalSecondAbbreviation[1]=SecDecInternalSecondAbbreviation[2] + SecDecInternalSecondAbbreviation[1];SecDecInternalSecondAbbreviation[2]=SecDecInternaldSecDecInternalDeformedx2d1Call1*SecDecInternaldSecDecInternalDeformedx3d3Call1;SecDecInternalSecondAbbreviation[3]=SecDecInternaldSecDecInternalDeformedx2d3Call1*SecDecInternaldSecDecInternalDeformedx3d1Call1;SecDecInternalSecondAbbreviation[2]=SecDecInternalSecondAbbreviation[2] - SecDecInternalSecondAbbreviation[3];SecDecInternalSecondAbbreviation[3]= - SecDecInternaldSecDecInternalDeformedx1d2Call1*SecDecInternalSecondAbbreviation[2];SecDecInternalSecondAbbreviation[4]=SecDecInternaldSecDecInternalDeformedx2d2Call1*SecDecInternaldSecDecInternalDeformedx3d3Call1;SecDecInternalSecondAbbreviation[5]=SecDecInternaldSecDecInternalDeformedx2d3Call1*SecDecInternaldSecDecInternalDeformedx3d2Call1;SecDecInternalSecondAbbreviation[4]=SecDecInternalSecondAbbreviation[4] - SecDecInternalSecondAbbreviation[5];SecDecInternalSecondAbbreviation[5]=SecDecInternaldSecDecInternalDeformedx1d1Call1*SecDecInternalSecondAbbreviation[4];SecDecInternalSecondAbbreviation[6]=SecDecInternaldSecDecInternalDeformedx2d2Call1*SecDecInternaldSecDecInternalDeformedx3d1Call1;SecDecInternalSecondAbbreviation[7]=SecDecInternaldSecDecInternalDeformedx2d1Call1*SecDecInternaldSecDecInternalDeformedx3d2Call1;SecDecInternalSecondAbbreviation[6]=SecDecInternalSecondAbbreviation[6] - SecDecInternalSecondAbbreviation[7];SecDecInternalSecondAbbreviation[7]= - SecDecInternaldSecDecInternalDeformedx1d3Call1*SecDecInternalSecondAbbreviation[6];SecDecInternalSecondAbbreviation[3]=SecDecInternalSecondAbbreviation[7] + SecDecInternalSecondAbbreviation[3] + SecDecInternalSecondAbbreviation[5];SecDecInternalSecondAbbreviation[3]=SecDecInternaldSecDecInternalDeformedx0d0Call1*SecDecInternalSecondAbbreviation[3];SecDecInternalSecondAbbreviation[2]=SecDecInternaldSecDecInternalDeformedx1d0Call1*SecDecInternalSecondAbbreviation[2];SecDecInternalSecondAbbreviation[5]=SecDecInternaldSecDecInternalDeformedx2d0Call1*SecDecInternaldSecDecInternalDeformedx3d3Call1;SecDecInternalSecondAbbreviation[7]=SecDecInternaldSecDecInternalDeformedx2d3Call1*SecDecInternaldSecDecInternalDeformedx3d0Call1;SecDecInternalSecondAbbreviation[5]=SecDecInternalSecondAbbreviation[5] - SecDecInternalSecondAbbreviation[7];SecDecInternalSecondAbbreviation[7]= - SecDecInternaldSecDecInternalDeformedx1d1Call1*SecDecInternalSecondAbbreviation[5];SecDecInternalSecondAbbreviation[8]=SecDecInternaldSecDecInternalDeformedx2d0Call1*SecDecInternaldSecDecInternalDeformedx3d1Call1;SecDecInternalSecondAbbreviation[9]=SecDecInternaldSecDecInternalDeformedx2d1Call1*SecDecInternaldSecDecInternalDeformedx3d0Call1;SecDecInternalSecondAbbreviation[8]=SecDecInternalSecondAbbreviation[8] - SecDecInternalSecondAbbreviation[9];SecDecInternalSecondAbbreviation[9]=SecDecInternaldSecDecInternalDeformedx1d3Call1*SecDecInternalSecondAbbreviation[8];SecDecInternalSecondAbbreviation[2]=SecDecInternalSecondAbbreviation[9] + SecDecInternalSecondAbbreviation[2] + SecDecInternalSecondAbbreviation[7];SecDecInternalSecondAbbreviation[2]=SecDecInternaldSecDecInternalDeformedx0d2Call1*SecDecInternalSecondAbbreviation[2];SecDecInternalSecondAbbreviation[4]= - SecDecInternaldSecDecInternalDeformedx1d0Call1*SecDecInternalSecondAbbreviation[4];SecDecInternalSecondAbbreviation[5]=SecDecInternaldSecDecInternalDeformedx1d2Call1*SecDecInternalSecondAbbreviation[5];SecDecInternalSecondAbbreviation[7]=SecDecInternaldSecDecInternalDeformedx2d0Call1*SecDecInternaldSecDecInternalDeformedx3d2Call1;SecDecInternalSecondAbbreviation[9]=SecDecInternaldSecDecInternalDeformedx2d2Call1*SecDecInternaldSecDecInternalDeformedx3d0Call1;SecDecInternalSecondAbbreviation[7]=SecDecInternalSecondAbbreviation[7] - SecDecInternalSecondAbbreviation[9];SecDecInternalSecondAbbreviation[9]= - SecDecInternaldSecDecInternalDeformedx1d3Call1*SecDecInternalSecondAbbreviation[7];SecDecInternalSecondAbbreviation[4]=SecDecInternalSecondAbbreviation[9] + SecDecInternalSecondAbbreviation[4] + SecDecInternalSecondAbbreviation[5];SecDecInternalSecondAbbreviation[4]=SecDecInternaldSecDecInternalDeformedx0d1Call1*SecDecInternalSecondAbbreviation[4];SecDecInternalSecondAbbreviation[5]=SecDecInternaldSecDecInternalDeformedx1d0Call1*SecDecInternalSecondAbbreviation[6];SecDecInternalSecondAbbreviation[6]= - SecDecInternaldSecDecInternalDeformedx1d2Call1*SecDecInternalSecondAbbreviation[8];SecDecInternalSecondAbbreviation[7]=SecDecInternaldSecDecInternalDeformedx1d1Call1*SecDecInternalSecondAbbreviation[7];SecDecInternalSecondAbbreviation[5]=SecDecInternalSecondAbbreviation[7] + SecDecInternalSecondAbbreviation[5] + SecDecInternalSecondAbbreviation[6];SecDecInternalSecondAbbreviation[5]=SecDecInternaldSecDecInternalDeformedx0d3Call1*SecDecInternalSecondAbbreviation[5];SecDecInternalSecondAbbreviation[2]=SecDecInternalSecondAbbreviation[5] + SecDecInternalSecondAbbreviation[4] + SecDecInternalSecondAbbreviation[3] + SecDecInternalSecondAbbreviation[2];

auto SecDecInternalUCall1 =SecDecInternalSecondAbbreviation[1];
auto SecDecInternallogCall4 =log(SecDecInternalSecDecInternalCondefFacx2Call1);
auto SecDecInternalSecDecInternalPowCall5 =pow(SecDecInternalSecDecInternalDeformedx0Call1,2);
auto SecDecInternalSecDecInternalPowCall6 =pow(SecDecInternalSecDecInternalDeformedx1Call1,2);
auto SecDecInternalSecDecInternalPowCall7 =pow(SecDecInternalSecDecInternalDeformedx3Call1,2);
auto SecDecInternalSecDecInternalCondefJacCall1 =SecDecInternalSecondAbbreviation[2];


// begin next dependency level
SecDecInternalSecondAbbreviation[1]=SecDecInternalAbbreviations2(9);SecDecInternalSecondAbbreviation[2]=SecDecInternalAbbreviations2(12);SecDecInternalSecondAbbreviation[3]=SecDecInternalSecDecInternalDeformedx0Call1 + SecDecInternalSecDecInternalDeformedx1Call1;SecDecInternalSecondAbbreviation[4]=m2*SecDecInternalSecDecInternalDeformedx2Call1;SecDecInternalSecondAbbreviation[5]=SecDecInternalSecondAbbreviation[3]*SecDecInternalSecondAbbreviation[4];SecDecInternalSecondAbbreviation[5]=SecDecInternalSecondAbbreviation[5] + m2;SecDecInternalSecondAbbreviation[6]=SecDecInternalSecDecInternalPowCall7 + 1.E+0;SecDecInternalSecondAbbreviation[5]=SecDecInternalSecondAbbreviation[5]*SecDecInternalSecondAbbreviation[6];SecDecInternalSecondAbbreviation[4]=SecDecInternalSecondAbbreviation[4]*SecDecInternalSecDecInternalDeformedx3Call1;SecDecInternalSecondAbbreviation[6]=SecDecInternalSecDecInternalDeformedx2Call1 + 1.E+0;SecDecInternalSecondAbbreviation[7]=SecDecInternalSecondAbbreviation[6]*m2;SecDecInternalSecondAbbreviation[4]=SecDecInternalSecondAbbreviation[4] + SecDecInternalSecondAbbreviation[7];SecDecInternalSecondAbbreviation[7]=SecDecInternalSecDecInternalPowCall5 + SecDecInternalSecDecInternalPowCall6;SecDecInternalSecondAbbreviation[4]=SecDecInternalSecondAbbreviation[4]*SecDecInternalSecondAbbreviation[7];SecDecInternalSecondAbbreviation[7]=SecDecInternalSecDecInternalDeformedx3Call1*SecDecInternalSecDecInternalDeformedx2Call1;SecDecInternalSecondAbbreviation[6]=SecDecInternalSecondAbbreviation[7] + SecDecInternalSecondAbbreviation[6];SecDecInternalSecondAbbreviation[6]=SecDecInternalSecDecInternalDeformedx1Call1*SecDecInternalSecondAbbreviation[6];SecDecInternalSecondAbbreviation[6]=SecDecInternalSecondAbbreviation[7] + SecDecInternalSecondAbbreviation[6];SecDecInternalSecondAbbreviation[6]=SecDecInternalSecDecInternalDeformedx0Call1*SecDecInternalSecondAbbreviation[6];SecDecInternalSecondAbbreviation[7]=SecDecInternalSecDecInternalDeformedx1Call1*SecDecInternalSecondAbbreviation[7];SecDecInternalSecondAbbreviation[6]=SecDecInternalSecondAbbreviation[6] + SecDecInternalSecDecInternalDeformedx3Call1 + SecDecInternalSecondAbbreviation[7];SecDecInternalSecondAbbreviation[6]=SecDecInternalSecondAbbreviation[2]*SecDecInternalSecondAbbreviation[6];SecDecInternalSecondAbbreviation[7]=SecDecInternalSecDecInternalDeformedx3Call1 + 1.E+0;SecDecInternalSecondAbbreviation[3]=SecDecInternalSecondAbbreviation[1]*SecDecInternalSecondAbbreviation[7]*SecDecInternalSecondAbbreviation[3];SecDecInternalSecondAbbreviation[3]=SecDecInternalSecondAbbreviation[3] + SecDecInternalSecondAbbreviation[6] + SecDecInternalSecondAbbreviation[4] + SecDecInternalSecondAbbreviation[5];

auto SecDecInternalFCall1 =SecDecInternalSecondAbbreviation[3];
auto SecDecInternallogCall5 =log(SecDecInternalUCall1);
auto SecDecInternalSecDecInternalDenominatorCall2 =SecDecInternalDenominator(SecDecInternalUCall1);


// begin next dependency level


auto SecDecInternallogCall3 =log(SecDecInternalFCall1);
auto SecDecInternalSecDecInternalDenominatorCall1 =SecDecInternalDenominator(SecDecInternalFCall1);


// begin final dependency level
SecDecInternalSecondAbbreviation[1]=SecDecInternalFCall1 -SecDecInternalFCall2;SecDecInternalSecondAbbreviation[2]=SecDecInternallogCall3 +SecDecInternallogCall2;SecDecInternalSecondAbbreviation[3]=SecDecInternallogCall5 +SecDecInternallogCall1;SecDecInternalSecondAbbreviation[2]= - SecDecInternallogCall4 +3.E+0*SecDecInternalSecondAbbreviation[3] - 2.E+0*SecDecInternalSecondAbbreviation[2];SecDecInternalSecondAbbreviation[2]=4.E+0*SecDecInternalSecDecInternalDenominatorCall2*SecDecInternalSecDecInternalDenominatorCall1*SecDecInternalSecDecInternalCondefJacCall1*SecDecInternalSecondAbbreviation[2];


// contour deformation sign checks
real_t SecDecInternalSignCheckExpression;
SecDecInternalSignCheckExpression = SecDecInternalImagPart(SecDecInternalSecondAbbreviation[1]);
#ifdef SECDEC_WITH_CUDA
if (SecDecInternalSignCheckExpression > 0) {printf("Sign check 1 (contour deformation polynomial) failed.");
return std::nan("");
}
#else
if (SecDecInternalSignCheckExpression > 0)throw secdecutil::sign_check_error(", \"contour deformation polynomial\", check id \"1\",");
#endif
SecDecInternalSignCheckExpression = SecDecInternalRealPart(SecDecInternalUCall1);
#ifdef SECDEC_WITH_CUDA
if (SecDecInternalSignCheckExpression < 0) {printf("Sign check 1 (positive polynomial)failed.");
return std::nan("");
}
#else
if (SecDecInternalSignCheckExpression < 0)throw secdecutil::sign_check_error(", \"positive polynomial\", check id \"1\",");
#endif
// end of contour deformation sign checks

tmp = SecDecInternalSecondAbbreviation[2];

return tmp;
#undef x0
#undef x1
#undef x2
#undef x3
#undef s
#undef m2
#undef SecDecInternalLambda0
#undef SecDecInternalLambda1
#undef SecDecInternalLambda2
#undef SecDecInternalLambda3
#undef SecDecInternalDenominator
#undef SecDecInternalRealPart
#undef SecDecInternalImagPart
#undef tmp
#undef SecDecInternalAbbreviations2
};
#ifdef SECDEC_WITH_CUDA
__device__ secdecutil::SectorContainerWithDeformation<real_t, complex_t>::DeformedIntegrandFunction* const device_sector_2_order_1_integrand = sector_2_order_1_integrand;
secdecutil::SectorContainerWithDeformation<real_t, complex_t>::DeformedIntegrandFunction* get_device_sector_2_order_1_integrand()
{
using IntegrandFunction = secdecutil::SectorContainerWithDeformation<real_t, complex_t>::DeformedIntegrandFunction;
IntegrandFunction* device_address_on_host;
auto errcode = cudaMemcpyFromSymbol(&device_address_on_host,device_sector_2_order_1_integrand, sizeof(IntegrandFunction*));
if (errcode != cudaSuccess) throw secdecutil::cuda_error( cudaGetErrorString(errcode) );
return device_address_on_host;
};
#endif
};
