integralfamilies:

  - name: "tree"
    loop_momenta: []

  # for boxes etc.
  - name: "A"
    loop_momenta: [k]
    propagators:
      - [ "k",        "mt^2"]
      - [ "k-p1",     "mt^2"]
      - [ "k-p1-p2",  "mt^2"]
      - [ "k-p3",     "mh^2"]

  # for heavy quark vertex correction etc.
#  - name: "B"
#    loop_momenta: [k]
#    propagators:
#      - [ "k",      "mh^2" ]
#      - [ "k-p1",     "mh^2"   ]
#      - [ "k-p1-p2",  "mh^2" ]
#      - [ "k-p3",     "mt^2"   ]
#
# 
#  - name: "C"
#    loop_momenta: [k]
#    propagators:
#      - [ "k",      "mt^2"]
#      - [ "k-p1",     "mt^2"   ]
#      - [ "k-p1-p2",  "mh^2" ]
#      - [ "k-p3",     "mh^2"   ]
#
#  - name: "D"
#    loop_momenta: [k]
#    propagators:
#      - [ "k",     "mh^2"]
#      - [ "k-p1",    "mh^2"   ]
#      - [ "k-p3",     "mt^2"   ]
#      - [ "k+p2-p3",  "mt^2" ]
#